language: node_js
node_js: 8.9.1
branches:
  only: master
cache: yarn
install: yarn
script:
- yarn build
- yarn test
deploy:
  api_key:
    secure: hbxBIxHho5g3WhyY5O9Mz83p0lGAY3yxyP2YMlbDwOp093PBgzCbW7FaJkw6+glOOiqsNgD+MHKedqilq7qeDByCFBhKs08Plo9QsAeAD8ZbCa9fF6fqUsqL7CSUD6i36WBYg+/zvWwJ1R4qqqlcjNCH6BgfQ/eGcRgltiODFF1wifTgF6F89rTpEMdP2IVZktlh2ilKFQ1pkOHmB4yNMHHYTdXhFF7SLV1jwkVGXNlpijkm7FsfCaR0xzC47AjUpE0lDrDyTrwxQB0ILGWfT/o5dGsZSWrvt3sKfiO5ZDjTQPqmbqz29Sdi55Jzx53K02I9seCc2QOqhg//jnyETfoM0jgNPmR1X5QcAKmGnOLc0oIA1yYV4Sl5ZMdpz8dYfItkgyG2sVAUq7YIxb95BNZVuZf2IqJJOCaPkySMawvNoQ4ehsZ3MT5pqescQR6e23h0uo8auM4x6E+RRv1B6ygYvjyM1YER96+j+ssor9q6i11Poo1vYQ1pPfWvjeOSQfcoagSSMuLVc5g7xDWEqMRAFBWaX4uA337we1ea1tryprSUDb452UzlaK7TiA4M5oSKr+MQXf8Cj3NGTKUfIZCiU2GqSVj52l4UWvS0AzRMvhHQZnhpcHpqn5sl4vh+naW0e5eKj1QbF9wS2+fi//l6hS8v7l55hbjuFj6P91M=
  email: npmjs@charlesstover.com
  on:
    branch: master
  provider: npm
  skip_cleanup: true
